In [1]:
#Modelagem Dimensional - Modelo Estrela
#Este notebook tem como objetivo transformar os dados tratados em um modelo dimensional (Star Schema), pronto para análise em ferramentas de BI como Power BI.

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('../data/processed/dados_tratados.csv')

df.head()

,id_internacao,id_procedimento,quantidade,custo_total,id_paciente,data_entrada,data_saida,setor,nome,idade,sexo,descricao,custo_unitario,tempo_internacao,custo_medio_item,ano,mes,dia,faixa_etaria
0,1,2,1,80,65,2024-09-20,2024-09-29,Centro Cirúrgico,Paciente_65,20,F,Exame de sangue,80,9,80.0,2024,9,20,Adulto
1,1,1,2,300,65,2024-09-20,2024-09-29,Centro Cirúrgico,Paciente_65,20,F,Consulta médica,150,9,150.0,2024,9,20,Adulto
2,1,5,3,900,65,2024-09-20,2024-09-29,Centro Cirúrgico,Paciente_65,20,F,Diária hospitalar,300,9,300.0,2024,9,20,Adulto
3,2,3,2,400,68,2024-05-12,2024-05-13,Emergência,Paciente_68,82,F,Raio-X,200,1,200.0,2024,5,12,Idoso
4,3,4,1,5000,90,2024-07-21,2024-07-27,Enfermaria,Paciente_90,7,F,Cirurgia,5000,6,5000.0,2024,7,21,Criança

In [4]:
df.columns

Index(['id_internacao', 'id_procedimento', 'quantidade', 'custo_total',
       'id_paciente', 'data_entrada', 'data_saida', 'setor', 'nome', 'idade',
       'sexo', 'descricao', 'custo_unitario', 'tempo_internacao',
       'custo_medio_item', 'ano', 'mes', 'dia', 'faixa_etaria'],
      dtype='object')

In [5]:
dim_paciente = df[['id_paciente', 'idade', 'sexo', 'faixa_etaria']] \
    .drop_duplicates() \
    .reset_index(drop=True)

dim_paciente.head()

   id_paciente  idade sexo faixa_etaria
0           65     20    F       Adulto
1           68     82    F        Idoso
2           90      7    F      Criança
3           21     73    M        Idoso
4            5     45    M       Adulto

In [6]:
dim_paciente = df[['id_paciente', 'idade', 'sexo', 'faixa_etaria']] \
    .drop_duplicates() \
    .reset_index(drop=True)

dim_paciente.head()

   id_paciente  idade sexo faixa_etaria
0           65     20    F       Adulto
1           68     82    F        Idoso
2           90      7    F      Criança
3           21     73    M        Idoso
4            5     45    M       Adulto

In [7]:
dim_tempo = df[['data_entrada', 'ano', 'mes', 'dia']] \
    .drop_duplicates() \
    .sort_values('data_entrada') \
    .reset_index(drop=True)

dim_tempo.columns = ['data', 'ano', 'mes', 'dia']

dim_tempo.head()

         data   ano  mes  dia
0  2024-01-01  2024    1    1
1  2024-01-06  2024    1    6
2  2024-01-08  2024    1    8
3  2024-01-09  2024    1    9
4  2024-01-12  2024    1   12

In [8]:
dim_tempo = df[['data_entrada', 'ano', 'mes', 'dia']] \
    .drop_duplicates() \
    .sort_values('data_entrada') \
    .reset_index(drop=True)

dim_tempo.columns = ['data', 'ano', 'mes', 'dia']

dim_tempo.head()

         data   ano  mes  dia
0  2024-01-01  2024    1    1
1  2024-01-06  2024    1    6
2  2024-01-08  2024    1    8
3  2024-01-09  2024    1    9
4  2024-01-12  2024    1   12

In [11]:
dim_procedimento = df[['id_procedimento', 'descricao']] \
    .drop_duplicates() \
    .reset_index(drop=True)

dim_procedimento.columns = ['id_procedimento', 'descricao_procedimento']

In [10]:
df.columns

Index(['id_internacao', 'id_procedimento', 'quantidade', 'custo_total',
       'id_paciente', 'data_entrada', 'data_saida', 'setor', 'nome', 'idade',
       'sexo', 'descricao', 'custo_unitario', 'tempo_internacao',
       'custo_medio_item', 'ano', 'mes', 'dia', 'faixa_etaria'],
      dtype='object')

In [13]:
dim_setor = df[['setor']] \
    .drop_duplicates() \
    .reset_index(drop=True)

dim_setor['id_setor'] = dim_setor.index + 1

dim_setor.head()

              setor  id_setor
0  Centro Cirúrgico         1
1        Emergência         2
2        Enfermaria         3
3               UTI         4

In [14]:
df = df.merge(dim_setor, on='setor', how='left')

In [15]:
fato = df[['id_internacao',
           'id_paciente',
           'id_procedimento',
           'id_setor',
           'data_entrada',
           'custo_total',
           'quantidade',
           'tempo_internacao']]

fato.head()

,id_internacao,id_paciente,id_procedimento,id_setor,data_entrada,custo_total,quantidade,tempo_internacao
0,1,65,2,1,2024-09-20,80,1,9
1,1,65,1,1,2024-09-20,300,2,9
2,1,65,5,1,2024-09-20,900,3,9
3,2,68,3,2,2024-05-12,400,2,1
4,3,90,4,3,2024-07-21,5000,1,6

In [16]:
dim_paciente.to_csv('../data/processed/dim_paciente.csv', index=False)
dim_tempo.to_csv('../data/processed/dim_tempo.csv', index=False)
dim_setor.to_csv('../data/processed/dim_setor.csv', index=False)
dim_procedimento.to_csv('../data/processed/dim_procedimento.csv', index=False)
fato.to_csv('../data/processed/fato_internacoes.csv', index=False)

In [ ]:
#Checagem de dados nulos

In [17]:
print(fato.isnull().sum())
print(fato.duplicated().sum())

id_internacao       0
id_paciente         0
id_procedimento     0
id_setor            0
data_entrada        0
custo_total         0
quantidade          0
tempo_internacao    0
dtype: int64
50

In [ ]:
#Checklist para validar se os dados estão aptos para seguir ao Power BI

In [18]:
fato[['id_paciente', 'id_setor', 'id_procedimento']].isnull().sum()

id_paciente        0
id_setor           0
id_procedimento    0
dtype: int64

In [ ]:
fato['id_setor'].isin(dim_setor['id_setor']).all()

In [19]:
fato['data_entrada'].min(), fato['data_entrada'].max()

('2024-01-01', '2024-12-30')